app/models/fornecedor.py
from app.extensions import db
from sqlalchemy import Integer, String
from sqlalchemy.orm import Mapped, mapped_column

class Fornecedor(db.Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    cnpj: Mapped[str] = mapped_column(String, nullable=False)
    nome: Mapped[int] = mapped_column(String, nullable=False)
    telefone: Mapped[float] = mapped_column(String, nullable=False)

    def __repr__(self):
        return f'<Fornecedor "{self.nome}">'

app/resources/fornecedor/__init__.py
from flask import Blueprint

bp = Blueprint('fornecedor', __name__)


from app.resources.fornecedor import routes

app/resources/fornecedor/routes.py
from flask import render_template, request, url_for, redirect
from app.resources.fornecedor import bp
from app.extensions import db
from app.models.fornecedor import Fornecedor


@bp.route("/", methods=("GET", "POST"))
def index():
    fornecedores = Fornecedor.query.all()

    if request.method == "POST":
        novo_fornecedor = Fornecedor(
            nome=request.form["nome"],
            cnpj=request.form["cnpj"],
            telefone=request.form["telefone"],
        )
        db.session.add(novo_fornecedor)
        db.session.commit()
        return redirect(url_for("fornecedor.index"))

    return render_template("fornecedor/index.html", fornecedores=fornecedores)


@bp.route("/<int:id>")
def delete(id):
    fornecedor = Fornecedor.query.get_or_404(id)
    db.session.delete(fornecedor)
    db.session.commit()
    return redirect(url_for("fornecedor.index"))


@bp.route("/search", methods=["POST"])
def search():
    search = f"%{request.form['search']}%"
    fornecedores = Fornecedor.query.filter(
        (Fornecedor.nome.like(search))
        | (Fornecedor.cnpj.like(search))
        | (Fornecedor.telefone.like(search))
    ).all()

    return render_template("fornecedor/index.html", fornecedores=fornecedores)


@bp.route("/detalhes/<int:id>", methods=("GET", "POST"))
def alterar_fornecedor(id):
    fornecedor = Fornecedor.query.get_or_404(id)
    if request.method == "POST":
        fornecedor = fornecedor.query.get_or_404(id)
        fornecedor.nome = (request.form["nome"],)
        fornecedor.cnpj = (request.form["cnpj"],)
        fornecedor.telefone = (request.form["telefone"],)
        db.session.commit()
    return render_template("fornecedor/alterar.html", fornecedor=fornecedor)

app/templates/fornecedor/alterar.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid mb-5">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="position-relative pb-3 text-center text-muted bg-body col-md-6">
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ url_for('static', filename = 'fornecedor.png') }}" class="img-fluid rounded-start" alt="..." />
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h1 class="card-title mb-3">{{ fornecedor.nome }}</h1>

                <form class="align-items-center form-floating" method="post" action="{{ url_for('fornecedor.alterar_fornecedor', id = fornecedor.id) }}">
                  <div class="row g-2">
                    <div class="col-md-12">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="nome" name="nome" value="{{ fornecedor.nome }}" />
                        <label for="nome">Nome</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="number" class="form-control" step="1" id="cnpj" name="cnpj" required value="{{ fornecedor.cnpj }}" />
                        <label for="quantidade">CNPJ</label>
                      </div>
                    </div>

                    <div class="form-floating">
                      <input type="text" class="form-control" id="telefone" name="telefone" required value="{{ fornecedor.telefone }}" />
                      <label for="codigobarra">Telefone</label>
                    </div>
                    <div class="row justify-content-end">
                      <button type="submit" class="btn col-md-4 mt-5 base-color">Alterar fornecedor</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/fornecedor/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid mb-5">
    <div class="row justify-content-center">
      <div class="position-relative pb-3 text-center text-muted bg-body border border-dashed rounded-5 col-md-5">
        <h1 class="text-body-emphasis mt-4 mb-4">Fornecedores</h1>
        <form class="row gx-3 gy-2 align-items-center" method="post" action="{{ url_for('fornecedor.index') }}">
          <div class="col-md-6">
            <input type="text" class="form-control" placeholder="Nome" id="nome" name="nome" required />
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control" step="0.1" placeholder="CNPJ" id="cnpj" name="cnpj" required />
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control" placeholder="Telefone" id="telefone" name="telefone" required />
          </div>
          <div class="row justify-content-end">
            <button type="submit" class="btn col-md-4 mt-5 base-color">Cadastrar fornecedor</button>
          </div>
        </form>
      </div>
    </div>

    <div class="row justify-content-center b-example-divider">
      <div class="col-md-3 mt-3">
        <form class="d-flex" action="{{ url_for('fornecedor.search') }}" method="post">
          <span class="input-group-text" id="basic-addon1" onclick="history.back()"><i class="bi bi-backspace"></i></span>
          <input class="form-control" type="search" placeholder="Nome, Cnpj ou telefone" aria-label="Search" name="search" id="search" />
          <button class="btn btn-outline-dark" type="submit">Procurar</button>
        </form>
      </div>
    </div>

    <div class="row g-3 pt-3 align-items-center justify-content-center">
      {% for fornecedor in fornecedores %}
        <div style="width: 20rem;">
          <div class="card overflow-hidden">
            <img src="{{ url_for('static', filename = 'fornecedor.png') }}" class="mx-auto d-block" alt="..." height="180rem" />
            <div class="card-body">
              <h5 class="card-title text-truncate" style="text-overflow: ellipsis;">{{ fornecedor.nome }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ fornecedor.cnpj }}</h6>
            </div>
            <ul class="list-group list-group-flush">
              <form class="row justify-content-center">
                <div class="col-md-12">
                  <span class="input-group-text" id="basic-addon1">Telefone</span>
                  <input class="form-control" type="text" value="{{ fornecedor.telefone }}" name="telefone" id="telefone" readonly />
                </div>
              </form>
            </ul>
            <div class="card-body text-end">
              <a href="{{ url_for('fornecedor.delete', id = fornecedor.id) }}" class="card-link btn btn-danger" type="button">Deletar</a>
              <a href="{{ url_for('fornecedor.alterar_fornecedor', id = fornecedor.id) }}" class="card-link btn btn-outline-secondary" type="button">Detalhes</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}