app/models/produto.py
import time
from app.extensions import db
from sqlalchemy import Integer, String, Float
from sqlalchemy.orm import Mapped, mapped_column

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


class ProdutoAnalytics:
    def __init__(self):
        self.options = webdriver.ChromeOptions()
        self.options.add_argument("--headless")
        self.options.add_argument("--no-sandbox")
        self.options.add_argument("enable-automation")
        self.options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Chrome(self.options)

    def get_imagem(self, nome):
        self.driver.get("https://images.google.com.br")
        elem = self.driver.find_element(By.ID, "APjFqb")
        elem.click()
        elem.send_keys(nome)
        elem.send_keys(Keys.ENTER)
        try:
            nome_elem = ".isv-r:nth-child(2) .rg_i"
            elem = self.driver.find_element(
                By.CSS_SELECTOR,
                nome_elem,
            )
            src = elem.get_attribute("src")
        except NoSuchElementException:
            src = "https://cdn-icons-png.flaticon.com/512/3163/3163203.png"
        return src

    def pesquisa_precos(self, nome):
        lista = []
        self.driver.get("https://shopping.google.com.br/")
        elem = self.driver.find_element(By.ID, "REsRA")
        elem.click()
        elem.send_keys(nome)
        elem.send_keys(Keys.ENTER)
        elem = self.driver.find_element(
            By.CLASS_NAME, "sh-pr__product-results-grid"
        )
        cards = elem.find_elements(By.CLASS_NAME, "sh-dgr__grid-result")
        for card in cards:
            valor = card.find_element(By.CLASS_NAME, "OFFNJ")
            vendedor = card.find_element(By.CLASS_NAME, "IuHnof")
            link = card.find_element(By.CLASS_NAME, "sh-dgr__offer-content").find_element(By.TAG_NAME, "a")
            img = card.find_element(By.CLASS_NAME, "sh-dgr__content").find_element(By.TAG_NAME, "img")
            nome = card.find_element(By.CLASS_NAME, "translate-content").find_element(By.TAG_NAME, "h3")

            lista.append(
                {
                    "vendedor": vendedor.text,
                    "valor_": int(re.findall("\\d+", valor.text)[0]),
                    "valor": valor.text,
                    "link": link.get_property("href"),
                    "img": img.get_property("src"),
                    "nome": nome.text,
                }
            )

        return lista

    def close(self):
        return self.driver.close()


class Produto(db.Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    nome: Mapped[str] = mapped_column(String, nullable=False)
    quantidade: Mapped[int] = mapped_column(Integer, nullable=False)
    preco: Mapped[float] = mapped_column(Float, nullable=False)
    codigobarra: Mapped[str] = mapped_column(String, nullable=False)
    img: Mapped[str] = mapped_column(String, nullable=False)
    marca: Mapped[str] = mapped_column(String, nullable=False)
    cor: Mapped[str] = mapped_column(String, nullable=True)

    def __repr__(self):
        return f'<Produto "{self.nome}">'

app/resources/produto/__init__.py
from flask import Blueprint

bp = Blueprint('produto', __name__)


from app.resources.produto import routes

app/resources/produto/routes.py
import operator
from flask import render_template, request, url_for, redirect
from app.resources.produto import bp
from app.extensions import db
from app.models.produto import Produto, ProdutoAnalytics


@bp.route("/", methods=("GET", "POST"))
def index():
    produtos = Produto.query.all()
    if request.method == "POST":
        analytics = ProdutoAnalytics()
        cor = request.form["cor"]
        nome = request.form["nome"]
        src = analytics.get_imagem(f"{nome} {cor}" if cor else nome)
        novo_produto = Produto(
            nome=request.form["nome"],
            preco=request.form["preco"],
            quantidade=request.form["quantidade"],
            codigobarra=request.form["codigobarra"],
            marca=request.form["marca"],
            cor=cor,
            img=src,
        )
        db.session.add(novo_produto)
        db.session.commit()
        return redirect(url_for("produto.index"))

    return render_template("produto/index.html", produtos=produtos)


@bp.route("/<int:id>")
def delete(id):
    produto = Produto.query.get_or_404(id)
    db.session.delete(produto)
    db.session.commit()
    return redirect(url_for("produto.index"))


@bp.route("/detalhes/<int:id>", methods=("GET", "POST"))
def alterar_produto(id):
    produto = Produto.query.get_or_404(id)
    analytics = ProdutoAnalytics()

    if request.method == "POST":
        produto = Produto.query.get_or_404(id)
        produto.nome = (request.form["nome"],)
        produto.preco = (request.form["preco"],)
        produto.quantidade = (request.form["quantidade"],)
        produto.codigobarra = (request.form["codigobarra"],)
        produto.marca = (request.form["marca"],)
        produto.cor = (request.form["cor"],)
        produto.img = analytics.get_imagem(
            f"{produto.nome} {produto.cor}" if produto.cor else produto.nome
        )
        db.session.commit()

    analytics = analytics.pesquisa_precos(
        f"{produto.nome} {produto.cor}" if produto.cor else produto.nome
    )

    if analytics:
        analytics = sorted(analytics, key=lambda x: x["valor_"])
    return render_template("produto/alterar.html", produto=produto, analytics=analytics)


@bp.route("/search", methods=["POST"])
def search():
    search = f"%{request.form['search']}%"
    produtos = Produto.query.filter(
        (Produto.nome.like(search))
        | (
            Produto.codigobarra.like(search)
            | (Produto.cor.like(search))
            | (Produto.marca.like(search))
        )
    ).all()

    return render_template("produto/index.html", produtos=produtos)

app/templates/produto/alterar.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid mb-5">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="position-relative pb-3 text-center text-muted bg-body col-md-6">
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ produto.img }}" class="img-fluid rounded-start" alt="..." />
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h1 class="card-title mb-3">{{ produto.nome }}</h1>

                <form class="align-items-center form-floating" method="post" action="{{ url_for('produto.alterar_produto', id = produto.id) }}">
                  <div class="row g-2">
                    <div class="col-md-12">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="nome" name="nome" value="{{ produto.nome }}" />
                        <label for="nome">Nome</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="number" class="form-control" step="1" id="quantidade" name="quantidade" required value="{{ produto.quantidade }}" />
                        <label for="quantidade">Quantidade</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="number" class="form-control" step=".01" id="preco" name="preco" required value="{{ produto.preco }}" />
                        <label for="preco">Valor</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="Marca" name="marca" required value="{{ produto.marca }}" />
                        <label for="Marca">Marca</label>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="cor" name="cor" value="{{ produto.cor }}" />
                        <label for="cor">Cor</label>
                      </div>
                    </div>
                    <div class="form-floating">
                      <input type="text" class="form-control" id="codigobarra" name="codigobarra" required value="{{ produto.codigobarra }}" />
                      <label for="codigobarra">Codigo de barra</label>
                    </div>
                    <div class="row justify-content-end">
                      <button type="submit" class="btn col-md-4 mt-5 base-color">Alterar produto</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="position-relative pb-3 text-muted bg-body col-md-4 overflow-auto" style="max-height: 600px">
        <div class="list-group">
          {% if analytics %}
            {% for analytic in analytics %}
              <a href="{{ analytic.link }}" class="list-group-item list-group-item-action" aria-current="true" target="_blank">
                <div class="d-flex w-100 justify-content-between">
                  <div class="col-md-2">
                    <img src="{{ analytic.img }}" class="rounded-start" alt="..." height="50rem" />
                  </div>
                  <div class="col-md-10">
                    <h5 class="mb-1">{{ analytic.vendedor }}</h5>
                    <small>{{ analytic.nome }}</small>
                    <div class="text-end">
                      <h5><span class="text-dark">{{ analytic.valor }}</span></h5>
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
          {% else %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">A pesquisa de preços está em andamento</h5>
                <small>agora</small>
              </div>
              <small>Volte em breve.</small>
              <div class="text-end">
                <h5><span class="text-dark"></span></h5>
              </div>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/produto/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid mb-5">
    <div class="row justify-content-center">
      <div class="position-relative pb-3 text-center text-muted bg-body border border-dashed rounded-5 col-md-5">
        <h1 class="text-body-emphasis mt-4 mb-4">Produtos</h1>

        <form class="row gx-3 gy-2 align-items-center" method="post" action="{{ url_for('produto.index') }}">
          <div class="col-md-12">
            <input type="text" class="form-control" placeholder="Nome" id="nome" name="nome" required />
          </div>
          <div class="col-md-4">
            <input type="number" class="form-control" step="1" placeholder="Quantidade" id="quantidade" name="quantidade" required />
          </div>
          <div class="col-md-4">
            <input type="number" class="form-control" step=".01" placeholder="Preco" id="preco" name="preco" required />
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control" placeholder="Marca" id="marca" name="marca" required />
          </div>
          <div class="col-md-6">
            <input type="text" class="form-control" placeholder="Cor" id="cor" name="cor" />
          </div>
          <div class="col-md-12">
            <input type="text" class="form-control" placeholder="Codigo de barra" id="codigobarra" name="codigobarra" required />
          </div>
          <div class="row justify-content-end">
            <button type="submit" class="btn col-md-4 mt-5 base-color">Cadastrar produto</button>
          </div>
        </form>
      </div>
    </div>

    <div class="row justify-content-center b-example-divider">
      <div class="col-md-3 mt-3">
        <form class="d-flex" action="{{ url_for('produto.search') }}" method="post">
          <span class="input-group-text" id="basic-addon1" onclick="history.back()"><i class="bi bi-backspace"></i></span>
          <input class="form-control" type="search" placeholder="Nome, codigo de barra, marca, cor" aria-label="Search" name="search" id="search" />
          <button class="btn btn-outline-dark" type="submit">Procurar</button>
        </form>
      </div>
    </div>

    <div class="row g-3 pt-3 align-items-center justify-content-center">
      {% for produto in produtos %}
        <div style="width: 20rem;">
          <div class="card overflow-hidden">
            <img src="{{ produto.img }}" class="mx-auto d-block" alt="..." height="180rem" />
            <div class="card-body">
              <h5 class="card-title text-truncate" style="text-overflow: ellipsis;">{{ produto.nome }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ produto.codigobarra }}</h6>
            </div>
            <ul class="list-group list-group-flush">
              <form class="row justify-content-center">
                <div class="col-md-6">
                  <span class="input-group-text" id="basic-addon1">Marca</span>
                  <input class="form-control" type="text" value="{{ produto.marca }}" name="marca" id="marca" readonly />
                </div>

                {% if produto.cor %}
                  <div class="col-md-6">
                    <span class="input-group-text" id="basic-addon1">Cor</span>
                    <input class="form-control" type="text" value="{{ produto.cor }}" name="cor" id="cor" readonly />
                  </div>
                {% endif %}
              </form>
              {% if produto.quantidade >= 10 and produto.quantidade < 20 %}
                <div class="toast-container position-fixed bottom-0 end-0 p-3 mb-3">
                  <div class="toast fade show">
                    <div class="toast-header bg-warning text-white">
                      <strong class="me-auto"><i class="bi bi-exclamation-triangle-fill" style="margin-left: 5px;"></i> Alerta de fim de estoque</strong>
                      <small>agora</small>
                      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body">
                      O item {{ produto.nome }} esta em fim de estoque <a href="{{ url_for('produto.alterar_produto', id = produto.id) }}" class="text-dark">Ver detalhes!</a>
                    </div>
                  </div>
                </div>
                <li class="list-group-item">
                  <h5><span class="badge bg-warning">{{ produto.quantidade }} unidades <i class="bi bi-dash-circle-fill" style="margin-left: 5px;"></i></span></h5>
                </li>
              {% elif produto.quantidade < 10 %}
                <div class="toast-container position-fixed bottom-0 end-0 p-3 mb-3">
                  <div class="toast fade show">
                    <div class="toast-header bg-danger text-white">
                      <strong class="me-auto"><i class="bi bi-exclamation-triangle-fill" style="margin-left: 5px;"></i> Alerta de estoque acabando</strong>
                      <small>agora</small>
                      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast"></button>
                    </div>
                    <div class="toast-body">
                      O item {{ produto.nome }} esta com poucas unidades <a href="{{ url_for('produto.alterar_produto', id = produto.id) }}" class="text-dark">Ver detalhes!</a>
                    </div>
                  </div>
                </div>
                <li class="list-group-item">
                  <h5><span class="badge bg-danger">{{ produto.quantidade }} unidades<i class="bi bi-exclamation-triangle-fill" style="margin-left: 5px;"></i></span></h5>
                </li>
              {% else %}
                <li class="list-group-item">
                  <h5><span class="badge bg-success">{{ produto.quantidade }} unidades<i class="bi bi-check-square-fill" style="margin-left: 5px;"></i></span></h5>
                </li>
              {% endif %}
              <li class="list-group-item text-end">
                <h3><span class="badge text-dark">R$ {{ produto.preco }}</span></h3>
              </li>
            </ul>
            <div class="card-body text-end">
              <a href="{{ url_for('produto.delete', id = produto.id) }}" class="card-link btn btn-danger" type="button">Deletar</a>
              <a href="{{ url_for('produto.alterar_produto', id = produto.id) }}" class="card-link btn btn-outline-secondary" type="button">Detalhes</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}